# Generated by Django 3.0.8 on 2020-07-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='jobi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=100),
        ),
    ]
