# Generated by Django 3.0.8 on 2020-07-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200728_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part time', 'Part time'), ('Full time', 'Full time')], max_length=100),
        ),
    ]
